### PR TITLE
Update Notion API endpoint

### PR DESCRIPTION
**Pull request by niekert**
### Description

Update endpoint for Notion API

### Testing

- [ ] Notion works
  - [ ] Logout of Notion
  - [ ] Run the local version of this branch
  - [ ] oAuth works

### CODE REVIEW

**Review by huntercaron — APPROVED** [review]

**Comment by huntercaron** [comment]
QA ✅

**Comment by huntercaron** [comment]
Not sure what I did actually?

Screenshot 2024-09-10 at 15 58 32

**Comment by huntercaron** [comment]
Worked second time tho

**Comment by niekert** [comment]
The 404 is when its polling for a token but there is no token yet and you are still in the auth flow. So expected behavior

**Pull request merged**
