### PR TITLE
Add Color Extract and Concentric

### PR DESCRIPTION
**Pull request by benjamindenboer**
### Description
This PR adds two new plugins to the default set for inspiration: **Concentric** and **Color Extract**. Concentric allows you to select a layer, and if it has a single child, it will allow you to tweak sliders to make their corner radii perfectly concentric, regardless of padding used. The Color Extract plugin allows you to select any images, and it will grab the dominant colors, which you can then apply to any layer, or convert the entire thing into a customizable linear gradient. This latter plugin is sticky, so you can freely select other objects and it will keep showing you the dominant colors of the last-selected image.

Artboard

### Testing
- [ ] Concentric: Confirm it disables for invalid selections
- [ ] Concentric: Confirm it correctly makes radii concentric with different paddings
- [ ] Concentric: Try testing it within dark and light app themes, confirm UI looks good
- [ ] Color Extract: Confirm it grabs colors across different images, with variable colors
- [ ] Color Extract: Confirm you can pick any solid color, or set a gradient
- [ ] Color Extract: Confirm the plugin is sticky, so it does not insta disable when selecting non-images
- [ ] Color Extract: Try testing it within dark and light app themes, confirm UI looks good

### CODE REVIEW

**Comment by huntercaron** [comment]
Lovelyy ty!

Could you move the icons for each Plugin into the "public" folder inside each Plugin? The path in framer.json is relative to that directory

**Review by huntercaron — COMMENTED** [review]
Could you update the readme files in each plugin to be a simple little info page like this? https://github.com/framer/plugins/tree/main/plugins/phosphor

**Review by huntercaron — APPROVED** [review]
LGTM, thank you! 👏

**Review by niekert — APPROVED** [review]
Very nice 😍

**Pull request merged**
